"""Action-to-Pydantic output converters: numpy actions -> domain model outputs."""

from __future__ import annotations

from datetime import date, datetime, timedelta
from uuid import UUID, uuid4

import numpy as np

from csc.models.capacity import (
    Campaign,
    CampaignStatus,
    CapacityCalendar,
    DepotCapacityPlan,
    PlantCapacityPlan,
)
from csc.models.common import (
    BatchStatus,
    OrderStatus,
    SupplyChainStage,
    UnitOfMeasure,
    Urgency,
)
from csc.models.demand import DemandPlan, SiteDemand
from csc.models.supply import Batch, InventoryPosition, SupplyOrder, SupplyPlan
from csc.orchestrator.state import PortfolioPlan, SharedState
from csc.rl.obs_builders import IndexMap, MAX_INVENTORY_POSITIONS, MAX_TRIAL_SITE_PAIRS


def map_demand_action(
    action: np.ndarray,
    state: SharedState,
    trial_site_map: IndexMap,
    current_month: date | None = None,
) -> DemandPlan:
    """Convert demand forecast actions to a DemandPlan.

    Action layout: [predicted_patients_0, predicted_kits_0, ..., predicted_patients_N, predicted_kits_N]
    """
    now = current_month or date.today().replace(day=1)
    site_demands: list[SiteDemand] = []
    demand_by_trial: dict[str, int] = {}

    idx = 0
    for trial in state.trials:
        trial_demand = 0
        for site_id in trial.sites:
            if idx >= len(trial_site_map):
                break

            # Get predictions from action
            pred_patients = max(0, int(round(action[idx * 2])))
            pred_kits = max(0, int(round(action[idx * 2 + 1])))

            # Find the finished good for this trial's first arm
            fg_id = _find_fg_for_trial(state, trial)
            if fg_id is None:
                idx += 1
                continue

            overage_kits = int(pred_kits * (1 + trial.overage_pct))
            safety_kits = max(1, int(pred_kits * 0.5))

            site_demands.append(SiteDemand(
                trial_id=trial.id,
                site_id=site_id,
                month=now,
                finished_good_id=fg_id,
                quantity_kits=pred_kits,
                quantity_with_overage=overage_kits,
                safety_stock_kits=safety_kits,
                urgency=Urgency.ROUTINE,
            ))
            trial_demand += overage_kits
            idx += 1

        demand_by_trial[trial.protocol_number] = trial_demand

    total_kits = sum(sd.quantity_with_overage for sd in site_demands)
    horizon_start = min((sd.month for sd in site_demands), default=now)
    horizon_end = max((sd.month for sd in site_demands), default=now) + timedelta(days=180)

    return DemandPlan(
        generated_at=datetime.now(),
        horizon_start=horizon_start,
        horizon_end=horizon_end,
        site_demands=site_demands,
        total_kit_demand=total_kits,
        demand_by_trial=demand_by_trial,
        assumptions=["Generated by RL demand forecasting agent"],
    )


def map_inventory_action(
    action: np.ndarray,
    state: SharedState,
    inv_map: IndexMap,
) -> SupplyPlan:
    """Convert inventory actions to a SupplyPlan (orders + inventory projections).

    Action layout: [reorder_qty_0, safety_target_0, ..., reorder_qty_N, safety_target_N]
    """
    orders: list[SupplyOrder] = []
    projections: list[InventoryPosition] = []
    shortfalls: list[str] = []
    now = date.today()

    positions = state.inventory_positions or []
    for i, pos in enumerate(positions[:MAX_INVENTORY_POSITIONS]):
        reorder_qty = max(0, float(action[i * 2]))
        safety_months = float(np.clip(action[i * 2 + 1], 0.5, 6.0))

        # Create reorder if quantity > 0
        if reorder_qty > 1.0:
            orders.append(SupplyOrder(
                material_id=pos.material_id,
                stage=_infer_stage(state, pos.material_id),
                quantity=reorder_qty,
                unit=UnitOfMeasure.UNITS,
                origin_id=pos.location_id,
                destination_id=pos.location_id,
                required_date=now + timedelta(days=30),
                ship_date=now + timedelta(days=7),
                status=OrderStatus.PLANNED,
            ))

        # Project inventory
        projected_available = pos.on_hand + reorder_qty - pos.allocated
        projected = InventoryPosition(
            material_id=pos.material_id,
            location_id=pos.location_id,
            on_hand=pos.on_hand + reorder_qty,
            in_transit=pos.in_transit,
            on_order=reorder_qty,
            allocated=pos.allocated,
            available=max(0, projected_available),
            days_of_supply=safety_months * 30,
        )
        projections.append(projected)

        if projected_available < 0:
            shortfalls.append(
                f"Shortfall for material {pos.material_id} at {pos.location_id}: "
                f"{abs(projected_available):.0f} units short"
            )

    return SupplyPlan(
        generated_at=datetime.now(),
        horizon_start=now,
        horizon_end=now + timedelta(days=180),
        batches=[],
        orders=orders,
        inventory_projections=projections,
        shortfall_alerts=shortfalls,
        reasoning=["Generated by RL inventory & safety stock agent"],
    )


def map_batch_action(
    action: np.ndarray,
    state: SharedState,
    line_map: IndexMap,
    mat_map: IndexMap,
) -> SupplyPlan:
    """Convert batch scheduling actions to a SupplyPlan (batches).

    Action layout per line: [material_idx, num_batches, batch_size_multiplier]
    """
    batches: list[Batch] = []
    now = date.today()
    n_materials = len(mat_map)

    lines = state.equipment_lines or []
    for i, line in enumerate(lines):
        if i >= len(line_map):
            break

        base = i * 3
        mat_idx = int(np.clip(round(action[base + 0]), 0, max(n_materials - 1, 0)))
        num_batches = int(np.clip(round(action[base + 1]), 0, 5))
        size_mult = float(np.clip(action[base + 2], 0.5, 1.5))

        if num_batches == 0 or mat_idx >= len(mat_map):
            continue

        mat_id = mat_map.uuid(mat_idx)
        nominal_batch = _get_nominal_batch(state, mat_id)
        stage = _infer_stage(state, mat_id)
        lead_days = _get_lead_days(state, mat_id)

        for b in range(num_batches):
            batch_qty = nominal_batch * size_mult
            start = now + timedelta(days=b * lead_days)
            end = start + timedelta(days=lead_days)
            expiry = end + timedelta(days=365)

            batches.append(Batch(
                material_id=mat_id,
                stage=stage,
                batch_number=f"RL-{line.name}-{mat_idx}-{b+1}",
                quantity=batch_qty,
                unit=UnitOfMeasure.UNITS,
                status=BatchStatus.PLANNED,
                planned_start=start,
                planned_end=end,
                expiry_date=expiry,
                location_id=line.location_id,
            ))

    return SupplyPlan(
        generated_at=datetime.now(),
        horizon_start=now,
        horizon_end=now + timedelta(days=365),
        batches=batches,
        orders=[],
        inventory_projections=[],
        shortfall_alerts=[],
        reasoning=["Generated by RL batch sizing & scheduling agent"],
    )


def map_capacity_action(
    action: np.ndarray,
    state: SharedState,
    loc_map: IndexMap,
    trl_map: IndexMap,
) -> tuple[DepotCapacityPlan, PlantCapacityPlan, PortfolioPlan]:
    """Convert capacity allocation actions to capacity plans.

    Action layout: allocation fraction matrix [n_locations * n_trials], row-major.
    """
    n_locations = len(loc_map)
    n_trials = len(trl_map)
    now_str = datetime.now().isoformat()
    now = date.today().replace(day=1)

    # Reshape and softmax-normalize per location
    raw = action[:n_locations * n_trials].reshape(n_locations, n_trials)
    alloc = np.zeros_like(raw)
    for loc_i in range(n_locations):
        row = raw[loc_i]
        exp_row = np.exp(row - np.max(row))
        alloc[loc_i] = exp_row / (exp_row.sum() + 1e-8)

    depot_calendars: list[CapacityCalendar] = []
    plant_calendars: list[CapacityCalendar] = []
    all_feasible = True

    plants_set = {p.id for p in state.plants}
    depots_set = {d.id for d in state.depots}

    for loc_i in range(n_locations):
        loc_id = loc_map.uuid(loc_i)
        util = float(alloc[loc_i].sum())
        if util > 1.0:
            all_feasible = False

        # Find location name
        loc_name = "Unknown"
        for p in state.plants:
            if p.id == loc_id:
                loc_name = p.name
                break
        for d in state.depots:
            if d.id == loc_id:
                loc_name = d.name
                break

        cal = CapacityCalendar(
            location_id=loc_id,
            location_name=loc_name,
            month=now,
            utilization_pct=min(util, 1.0) * 100,
            available_slots=max(0, int((1.0 - util) * 22)),
            reasoning=[f"RL-allocated {util:.1%} utilization across {n_trials} trials"],
        )

        if loc_id in plants_set:
            plant_calendars.append(cal)
        elif loc_id in depots_set:
            depot_calendars.append(cal)

    adjustments = []
    if not all_feasible:
        adjustments.append("Some locations exceed 100% utilization — consider redistributing.")

    depot_plan = DepotCapacityPlan(
        generated_at=now_str,
        depot_calendars=depot_calendars,
        feasible=all_feasible,
        adjustments=adjustments,
        reasoning=["Generated by RL capacity allocation agent"],
    )
    plant_plan = PlantCapacityPlan(
        generated_at=now_str,
        plant_calendars=plant_calendars,
        feasible=all_feasible,
        adjustments=adjustments,
        reasoning=["Generated by RL capacity allocation agent"],
    )

    # Build portfolio plan from priority-weighted allocations
    ranked_trials = []
    priority_map = {"phase_iii": 3, "phase_ii": 2, "phase_i": 1}
    for i, trial in enumerate(state.trials[:n_trials]):
        trial_alloc = float(alloc[:, i].sum()) / max(n_locations, 1)
        ranked_trials.append({
            "trial_id": str(trial.id),
            "protocol_number": trial.protocol_number,
            "priority_score": priority_map.get(trial.phase.value, 1),
            "capacity_allocation": round(trial_alloc, 3),
        })
    ranked_trials.sort(key=lambda t: t["priority_score"], reverse=True)

    portfolio_plan = PortfolioPlan(
        generated_at=datetime.now(),
        ranked_trials=ranked_trials,
        conflicts=[],
        synergies=[],
        resource_allocations=[],
        reasoning=["Generated by RL capacity allocation agent"],
    )

    return depot_plan, plant_plan, portfolio_plan


# ── Helpers ──────────────────────────────────────────────────────────────────

def _find_fg_for_trial(state: SharedState, trial) -> UUID | None:
    """Find a finished good ID associated with a trial's first arm."""
    if not trial.arms:
        return None
    dp_id = trial.arms[0].drug_product_id
    for pp in state.materials.primary_packs:
        if pp.drug_product_id == dp_id:
            for fg in state.materials.finished_goods:
                if fg.primary_pack_id == pp.id:
                    return fg.id
    return None


def _infer_stage(state: SharedState, material_id: UUID) -> SupplyChainStage:
    """Infer the supply chain stage for a material."""
    cat = state.materials
    for ds in cat.drug_substances:
        if ds.id == material_id:
            return SupplyChainStage.DRUG_SUBSTANCE
    for dp in cat.drug_products:
        if dp.id == material_id:
            return SupplyChainStage.DRUG_PRODUCT
    for pp in cat.primary_packs:
        if pp.id == material_id:
            return SupplyChainStage.PRIMARY_PACK
    for fg in cat.finished_goods:
        if fg.id == material_id:
            return SupplyChainStage.FINISHED_GOOD
    return SupplyChainStage.FINISHED_GOOD


def _get_nominal_batch(state: SharedState, material_id: UUID) -> float:
    """Get the nominal batch size for a material."""
    cat = state.materials
    for ds in cat.drug_substances:
        if ds.id == material_id:
            return ds.batch_size_kg
    for dp in cat.drug_products:
        if dp.id == material_id:
            return float(dp.batch_size_units)
    for pp in cat.primary_packs:
        if pp.id == material_id:
            return float(pp.pack_size)
    return 100.0


def _get_lead_days(state: SharedState, material_id: UUID) -> int:
    """Get manufacturing lead time in days for a material."""
    cat = state.materials
    for ds in cat.drug_substances:
        if ds.id == material_id:
            return ds.manufacturing_lead_time_days + ds.qc_release_time_days
    for dp in cat.drug_products:
        if dp.id == material_id:
            return dp.manufacturing_lead_time_days + dp.qc_release_time_days
    for pp in cat.primary_packs:
        if pp.id == material_id:
            return pp.packaging_lead_time_days
    for fg in cat.finished_goods:
        if fg.id == material_id:
            return fg.labeling_lead_time_days
    return 30
